- rchain-coop/src/views/platform.hbs
- rchain-coop/src/views/portfolio.hbs
@ian-bloom please  verify my work.
- changes are:
- removed pithia form portfolio page
> Training session

- developer-rchain-coop/views/index.hbs
> Fix Jira WEB-141

- developer-rchain-coop/views/token-swap.hbs
Updated timeline information in Intro, Key Milestones, and Change Log.
> Fix Jira WEB-140

- developer-rchain-coop/src/views/token-swap.hbs
> Fix Web-140

- k8-spec/certificate.yaml
> fix provision certs for forum2

- rchain-coop/src/views/index.hbs
Updated home page by removing animated gifs and cleaning up text for simplicity.
> Derek dev branch

- developer-rchain-coop/src/views/index.hbs
At Kelly Foster's request: https://rchain.atlassian.net/browse/WEB-145
> FIX Update Get Started with RNode v0.8.2 release

- developer-rchain-coop/src/views/index.hbs
Updated the files for RNode v.08.3 as per Kelly Foster's request.
> FIX Updates to RNode v0.8.3

- k8-spec/ingress.yaml
See Issue #39 Create FAQ site at faq.rchain.coop
> [INTERNAL] Configure faq.rchain.coop ingress

- k8-spec/certificate.yaml
See Issue #39 Create FAQ site at faq.rchain.coop
> [FIX] faq certs

- developer-rchain-coop/src/views/validation.hbs
Changed Q1 to Q2 for main net launch.
> FIx Q1 citation

- developer-rchain-coop/src/views/index.hbs
Updated RNode 0.8.4 packages per Kelly Foster.
> Updated RNode 0.8.4 links

- developer-rchain-coop/src/views/index.hbs
Updated all links to RNode v0.8.5.
> Update to RNode v0.8.5

- developer-rchain-coop/src/views/layout.hbs
- rchain-coop/src/views/community.hbs
- rchain-coop/src/views/rchain-cooperative.hbs
See Issue: FIX Telegram invitation link #44
> FIX Update Telegram URL

- developer-rchain-coop/src/views/index.hbs
> Update RNode v0.9.1

- rchain-coop/src/views/team.hbs
Updated Board of Directors by adding Mark Pui and Ravi Srivatsav, removing Kenny Rowe and Kevin Goldstein.
> Added Ravi Srivatsav and Mark Pui to Team page

- rchain-coop/src/views/team.hbs
Added Steve Ross-Talbot to Team page
> Added Steve Ross-Talbot to Team page

- rchain-coop/src/views/team.hbs
Updated Mark Pui photo on Team page
> Updated Mark Pui photo

- rchain-coop/src/views/team.hbs
Fixed Mark Pui photo extension
> Fixed Mark Pui photo extension

- developer-rchain-coop/src/views/index.hbs
> Updated to RNode v0.9.2

- rchain-coop/src/views/index.hbs
Added test net link to home page
> Added test net link to home page

- developer-rchain-coop/src/views/index.hbs
> Updated to RNode v0.9.3

- developer-rchain-coop/src/views/validation.hbs
import the live HubSpot validator signup form into https://developer.rchain.coop/validation
> [FIX] replace validator interest form

- rchain-coop/src/views/team.hbs
Removed Barry Cynamon and Mark Pui from Board listing
> Removed Barry Cynamon and Mark Pui

- developer-rchain-coop/src/views/index.hbs
Removed sentence with past deadline
> Removed sentence with past deadline

- developer-rchain-coop/src/views/token-swap.hbs
Updated main net launch to Q3 2019
> Updated main net launch

- developer-rchain-coop/src/views/index.hbs
Update main net launch to Q3 2019
> Update main net launch

- developer-rchain-coop/src/views/index.hbs
> Update to RNode v0.9.5

- developer-rchain-coop/src/views/index.hbs
> Update to RNode v0.9.6

- developer-rchain-coop/src/views/index.hbs
> Update to RNode v0.9.7

- rchain-coop/src/views/success.hbs
> Removed three stubs from page

- rchain-coop/src/views/community.hbs
> Removed redundant text

- rchain-coop/src/views/success.hbs
> Removed logo from bottom of page

- rchain-coop/src/views/community.hbs
Aligning the Convertkit API to center.
> Center aligned API

- rchain-coop/src/views/community.hbs
> Revert "Center aligned API"

- developer-rchain-coop/src/views/index.hbs
> Updated to RNode v0.9.8

- developer-rchain-coop/src/views/index.hbs
> Update to RNode v0.9.9

- developer-rchain-coop/src/views/index.hbs
Updated calendar tile: removed meetups and changed time designations.
> Updated calendar tile

- developer-rchain-coop/src/views/faq.hbs
> Updated FAQ page

- developer-rchain-coop/src/views/index.hbs
> Updated to RNode v0.9.10

- rchain-coop/src/views/team.hbs
> Added Eric Meng to Board

- rchain-coop/src/views/team.hbs
Updated Eric Meng's name on bio
> Updated Eric Meng's name on bio

- developer-rchain-coop/src/views/index.hbs
> RNode Update

- developer-rchain-coop/src/views/index.hbs
> [Fix] Update index.hbs

- developer-rchain-coop/src/views/index.hbs
> Update to RNode v0.9.12

- developer-rchain-coop/src/views/faq.hbs
> [FIX] Remove link to Readthedocs

- developer-rchain-coop/src/views/index.hbs
> Updated to RNode v0.9.13

- developer-rchain-coop/src/views/token-swap.hbs
> update REV issuance

- rchain-coop/package.json
- rchain-coop/src/views/layout.hbs
Complements to @tet#5669 for suggesting.
> Warning banner.

- rchain-coop/src/views/layout.hbs
> FIX banner

- developer-rchain-coop/src/views/token-swap.hbs
source: [LGM in #announcements](https://discord.com/channels/375365542359465989/555123318177660928/681886875518107705)
this is a small edit to help with #125
> main net launch was Feb 25

- developer-rchain-coop/src/views/token-swap.hbs
added REV as of May 13, 2020
[https://hotbit.zendesk.com/hc/en-us/articles/360047538034-](https://hotbit.zendesk.com/hc/en-us/articles/360047538034-)
> FIX - Add HotBit Exchange

- developer-rchain-coop/src/views/token-swap.hbs
- rchain-coop/src/views/layout.hbs
Portfolios will be replaced by **Showcase**
> FIX: Comment out "Portfolios" from rchain.coop

- rchain-coop/src/routes/index.js
> Revert "[FIX] redirect member-invoice to community"
